#YAML 1.1
---
basic_tower:
  range: 50
  projectile: basic_bullet
  upgrade: med_tower

med_tower:
  range: 75
  projectile: strong_bullet
  upgrade: None

advanced_tower:
  range: 100
  projectile: ultra_bullet
  upgrade: None

basic_tower_train:
  sequence:
    - basic_tower
    - med_tower
    - advanced_tower