start_screen:
  x: 0
  y: 0
  width: 1
  height: 1
  inner_panels:
    - center_column:
        x: 0.4
        y: 0
        width: 0.2
        height: 1.0
        inner_panels:
          - play:
              x: 0
              y: 0.3
              width: 1.0
              height: 0.1
          - help:
              x: 0
              y: 0.6
              width: 1.0
              height: 0.1