start_screen:
  class: &layout game.subsystems.ui.layout.layout@Layout
  orientation: vertical
  inner_panels:
    - top:
        class: &panel game.subsystems.ui.layout.panel@Panel
        weight: 0.5
    - bottom:
        class: *panel
        weight: 0.5
