start_screen: #this is a comment
  orientation: horizontal
  panels:
    - left_padding:
        weight: &padding_amount 30%
    - button_area:
        weight: pass
        orientation: vertical
        panels:
          - top_padding:
              weight: *padding_amount
          - button:
              weight: pass
              fill:
                type: button
                text: play
                id: play_button
          - bottom_padding:
              weight: *padding_amount
    - right_padding:
        weight: *padding_amount

game_screen:
  orientation: vertical
  panels:
    - game_area:
        weight: 80%
    - shop_area:
        orientation: horizontal
        panels:
          - money:
              weight: 50%
          - health:
              weight: 50%